[functions]

  [functions."/summarize"]
    external_node_modules = []  # Optional list of external dependencies
    runtime = "python"  # Specify runtime as "python"

    # Other specific function configuration options (if needed)

